// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteEvent(arg1:string):Promise<void>;

export function EditEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ListEvents():Promise<Array<main.Event>>;
